name: 'SOOS DAST'
author: 'SOOS'
description: 'The affordable no limit web vulnerability scanner.'
branding:
  icon: "alert-triangle"
  color: "blue"

inputs:

  client_id:
    description: 'SOOS Client Id'
    required: true
  api_key:
    description: 'SOOS API Key'
    required: true
  project_name:
    description: 'SOOS project name'
    required: true
  scan_mode:
    description: 'SOOS DAST scan mode. Values available: baseline, fullscan, or apiscan'
    required: true
    default: 'baseline'
  api_url:
    description: 'SOOS API URL'
    required: true
    default: 'https://api.soos.io/api/'
  target_url:
    description: ''
    required: true
  debug:
    description: 'show debug messages'
    required: false
    default: 'false'
  ajax_spider:
    description: ' use the Ajax spider in addition to the traditional one'
    required: false
    default: 'false'
  rules:
    description: 'rules file to use to INFO, IGNORE or FAIL warnings'
    required: false
  context_file:
    description: 'context file which will be loaded prior to scanning the target'
    required: false
  context_user:
    description: 'username to use for authenticated scans - must be defined in the given context file'
    required: false
  full_scan_minutes:
    description: ''
    required: false
  api_scan_format:
    description: ''
    required: false
  active_scan_level:
    description: 'minimum level to show: PASS, IGNORE, INFO, WARN or FAIL'
    required: false
    default: 'PASS'
  zap_options:
    description: 'ZAP Additional Options'
    required: false
  request_cookies:
    description: 'Set Cookie values for the requests to the target URL'
    required: false
  request_header:
    description: 'Set extra header requests'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'

  args:
    - ${{ format('--clientId={0}', inputs.client_id) }}
    - ${{ format('--apiKey={0}', inputs.api_key) }}
    - ${{ format('--projectName={0}', inputs.project_name) }}
    - ${{ format('--scanMode={0}', inputs.scan_mode) }}
    - ${{ format('--apiURL={0}', inputs.api_url) }}
    - --integrationName="Github Action"
    - ${{ inputs.target_url }}
