name: 'SOOS DAST'
author: 'SOOS'
description: 'The affordable no limit web vulnerability scanner.'

inputs:

  client_id:
    description: ''
    required: true
  api_key:
    description: ''
    required: true
  project_name:
    description: ''
    required: true
  scan_mode:
    description: ''
    required: true
    default: 'baseline'
  api_url:
    description: ''
    required: true
    default: 'https://api.soos.io/api/'
  target_url:
    description: ''
    required: true
  debug:
    description: ''
    required: false
    default: 'false'
  ajax_spider:
    description: ''
    required: false
    default: 'false'
  rules:
    description: ''
    required: false
  context_file:
    description: ''
    required: false
  context_user:
    description: ''
    required: false
  full_scan_minutes:
    description: ''
    required: false
  api_scan_format:
    description: ''
    required: false
  active_scan_level:
    description: ''
    required: false
    default: 'PASS'

runs:
  using: 'docker'
  image: 'Dockerfile'

  args:
    - ${{ format('--clientId={0}', inputs.client_id) }}
    - ${{ format('--apiKey={0}', inputs.api_key) }}
    - ${{ format('--projectName={0}', inputs.project_name) }}
    - ${{ format('--scanMode={0}', inputs.scan_mode) }}
    - ${{ format('--apiURL={0}', inputs.api_url) }}
    - ${{ inputs.debug == true && '--debug' || null }}
    - ${{ inputs.ajax_spider == true && '--ajaxSpider' || null }}
    - ${{ inputs.rules != '' && format('--rules={0}', inputs.rules) || null }}
    - --integrationName="Github Action"
    - ${{ inputs.target_url }}
